### ISSUE TITLE
Wrong pin in Motordriver.cpp

### ISSUE THREAD

**Issue by maarbu** [Seeed-Studio/SeeedMotorShieldV2#1]
Motordriver.cpp has pin 9 assigned for both cases.  Lines 112,118,124 should have pin 10 defined.

**Comment by maarbu** [comment]
I set up a Pull request (I think. first time contributor through GitHub web)

**Comment by runner15** [comment]
Yes, I also did a pull request before I saw yours (new to that stuff).  This issue makes only 1 motor usable, and motor_id=1 not viable

**Comment by tapnair** [comment]
I was just going to post the same thing.  Was there resolution here?

**Comment by runner15** [comment]
There are 2 pull requests, but they have not been merged yet.
